name: CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]
    types: [opened, edited, reopened, synchronize]

  workflow_dispatch:

jobs:
  lint_test_continue:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run lint
      - run: yarn test